#!/usr/bin/env bash

set -o errexit

# Download LUX (http://mcmahan.io/lux)
# Includes Munroe color corpus with train/dev/test split
if [ ! -e rugstk ]; then
  echo 'Downloading LUX...'
  wget http://paul.rutgers.edu/~bcm84/rugstk_v1.0.tar.gz
  echo 'Extracting...'
  tar xzf rugstk_v1.0.tar.gz
  mv rugstk_v1 rugstk
  rm rugstk_v1.0.tar.gz
fi

echo 'Installing Python module dependencies...'
pip install ConfigArgParse pyhocon pypng 'Protobuf>=3.0.0b2'

if [ ! -e tensorflow ]; then
    echo 'Checking for tensorboard protos...'
    ( python -c 'import tensorflow.core.util.event_pb2' >/dev/null 2>&1 ) || (
        echo "It looks like you don't have TensorFlow installed, so I'm putting a"
        echo "symlink at ./tensorflow/ to just the bare minimum you need. If you"
        echo "decide to install Tensorflow in the future, you can remove it."
        ln -s third-party/tensorflow tensorflow
    )
fi

echo 'Installing testing modules (optional)...'
pip install nose nose-exclude coverage
