#!/usr/bin/env bash
set -o errexit
shopt -s failglob

if [[ "$#" != "1" ]]; then
  echo 'Usage: get_data <run_dir>'
  exit -2
fi

run_dir="$1"

l_data="$(echo runs/data_l/data.*.jsons)"
s_data="$(echo runs/data_s/data.*.jsons)"

if [[ $(grep '"listener": true,' config.json) ]]; then
  data="$l_data"
else
  data="$s_data"
fi

for data_path in $data; do
  filename="$(basename "$data_path")"
  ln -s --relative "$data_path" "$run_dir"/"$filename"
done
